language: python
python:
  - "3.3"
# cache:
#   directories:
#     - /home/travis/virtualenv/python3.3/lib/python3.3/site-packages
#     - $HOME/.pip-cache/
before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - pip install cython
  - pip install oursql
install:
  - pip install -r requirements.txt
before_script:
  - mysql --user=root -e "CREATE DATABASE ideabin;"
  - mysql --user=root -e "CREATE USER 'user123'@'localhost' IDENTIFIED BY 'pass123'";
  - mysql --user=root -e "GRANT ALL PRIVILEGES ON * . * TO 'user123'@'localhost'";
script: python test.py
sudo: false
