language: python
python:
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt
before_script:
  - mysql --user=root -e "CREATE DATABASE ideabin;"
  - mysql --user=root -e "CREATE USER 'user123'@'localhost' IDENTIFIED BY 'pass123'";
  - mysql --user=root -e "GRANT ALL PRIVILEGES ON * . * TO 'user123'@'localhost'";
script: python test.py
sudo: false
