"""
String to Text type
Revision ID: 1063da2f77
Revises: cc98a97380
Create Date: 2014-10-12 06:30:05.959144
"""
# revision identifiers, used by Alembic.
revision = '1063da2f77'
down_revision = 'cc98a97380'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'idea', 'story', type_=sa.Text, existing_type=sa.String(length=120))
    op.alter_column(
        'idea', 'desc', type_=sa.Text, existing_type=sa.String(length=1000))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'idea', 'story', type_=sa.String(length=120), existing_type=sa.Text)
    op.alter_column(
        'idea', 'desc', type_=sa.String(length=1000), existing_type=sa.Text)
    ### end Alembic commands ###
