"""

Other notification tables

Revision ID: 16088d721b4

Revises: 474a0170e40

Create Date: 2014-11-12 18:27:44.305674

"""

# revision identifiers, used by Alembic.

revision = '16088d721b4'

down_revision = '474a0170e40'



from alembic import op

import sqlalchemy as sa



def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notif_idea_update',
    sa.Column('notif_id', sa.UUID(), nullable=False),
    sa.Column('user_by', sa.UUID(), nullable=False),
    sa.Column('user_to', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.idea_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_by'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_to'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notif_id')
    )
    op.create_table('notif_comment_on_idea',
    sa.Column('notif_id', sa.UUID(), nullable=False),
    sa.Column('user_by', sa.UUID(), nullable=False),
    sa.Column('user_to', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.comment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.idea_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_by'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_to'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notif_id')
    )
    op.create_table('notif_comment_by_user',
    sa.Column('notif_id', sa.UUID(), nullable=False),
    sa.Column('user_by', sa.UUID(), nullable=False),
    sa.Column('user_to', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.comment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.idea_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_by'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_to'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notif_id')
    )
    ### end Alembic commands ###



def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notif_comment_by_user')
    op.drop_table('notif_comment_on_idea')
    op.drop_table('notif_idea_update')
    ### end Alembic commands ###

