"""
voting
Revision ID: 20a2d7d00e4
Revises: 342e8c935de
Create Date: 2014-11-02 15:46:01.829629
"""
# revision identifiers, used by Alembic.
revision = '20a2d7d00e4'
down_revision = '342e8c935de'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.idea_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'idea_id')
    )
    op.alter_column('user', 'facebook_url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True,
               existing_server_default='')
    op.alter_column('user', 'github_url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True,
               existing_server_default='')
    op.alter_column('user', 'role',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True,
               existing_server_default='Noob')
    op.alter_column('user', 'twitter_url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True,
               existing_server_default='')
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'twitter_url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False,
               existing_server_default='')
    op.alter_column('user', 'role',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False,
               existing_server_default='Noob')
    op.alter_column('user', 'github_url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False,
               existing_server_default='')
    op.alter_column('user', 'facebook_url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False,
               existing_server_default='')
    op.drop_table('vote')
    ### end Alembic commands ###
