"""

comments

Revision ID: 220e35d329b

Revises: 297bbb0bc1

Create Date: 2014-10-21 20:02:53.450801

"""

# revision identifiers, used by Alembic.

revision = '220e35d329b'

down_revision = '297bbb0bc1'



from alembic import op

import sqlalchemy as sa

from sqlalchemy.dialects import mysql

def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('desc_md', sa.Text(), nullable=False),
    sa.Column('desc_html', sa.Text(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.idea_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.alter_column('tag', 'tagname',
               existing_type=mysql.VARCHAR(collation='utf32_unicode_ci', length=50),
               nullable=False)
    ### end Alembic commands ###



def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag', 'tagname',
               existing_type=mysql.VARCHAR(collation='utf32_unicode_ci', length=50),
               nullable=True)
    op.drop_table('comment')
    ### end Alembic commands ###

