"""
desc md and html
Revision ID: 27ad2d72520
Revises: 1063da2f77
Create Date: 2014-10-12 17:15:30.125534
"""
# revision identifiers, used by Alembic.
revision = '27ad2d72520'
down_revision = '1063da2f77'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea', sa.Column('desc_html', sa.Text(), nullable=False))
    op.add_column('idea', sa.Column('desc_md', sa.Text(), nullable=False))
    op.drop_column('idea', 'desc')
    op.drop_column('idea', 'story')
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea', sa.Column('story', mysql.TEXT(collation='utf32_unicode_ci'), nullable=True))
    op.add_column('idea', sa.Column('desc', mysql.TEXT(collation='utf32_unicode_ci'), nullable=True))
    op.drop_column('idea', 'desc_md')
    op.drop_column('idea', 'desc_html')
    ### end Alembic commands ###
