"""

unique tagname

Revision ID: 297bbb0bc1

Revises: dfe9914968

Create Date: 2014-10-19 05:08:09.728270

"""

# revision identifiers, used by Alembic.

revision = '297bbb0bc1'

down_revision = 'dfe9914968'



from alembic import op

import sqlalchemy as sa



def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'tag', 'tagname', type_=sa.String(length=50), existing_type=sa.String(length=500))
    op.create_unique_constraint(None, 'tag', ['tagname'])
    ### end Alembic commands ###



def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'tag', 'tagname', type_=sa.String(length=500), existing_type=sa.String(length=50))
    op.drop_constraint(None, 'tag')
    ### end Alembic commands ###

