"""
tags-n-tagging
Revision ID: 3f95b7af313
Revises: 27ad2d72520
Create Date: 2014-10-16 18:49:41.740040
"""
# revision identifiers, used by Alembic.
revision = '3f95b7af313'
down_revision = '27ad2d72520'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('tagname', sa.String(length=500), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    ### end Alembic commands ###
