"""
Basic User table
Revision ID: 428446e4e16
Revises: None
Create Date: 2014-08-03 03:50:19.193368
"""
# revision identifiers, used by Alembic.
revision = '428446e4e16'
down_revision = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('blog_url', sa.String(length=120), nullable=True),
    sa.Column('profile_fb', sa.String(length=120), nullable=True),
    sa.Column('profile_twitter', sa.String(length=120), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_login_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
