"""

Remove vote_count

Revision ID: 466f4d318cd

Revises: 20a2d7d00e4

Create Date: 2014-11-02 20:16:00.454727

"""

# revision identifiers, used by Alembic.

revision = '466f4d318cd'

down_revision = '20a2d7d00e4'



from alembic import op

import sqlalchemy as sa

from sqlalchemy.dialects import mysql

def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idea', 'vote_count')
    ### end Alembic commands ###



def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea', sa.Column('vote_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###

