"""

NotifIdeaByUser

Revision ID: 474a0170e40

Revises: 59af27b681f

Create Date: 2014-11-11 23:46:36.720933

"""

# revision identifiers, used by Alembic.

revision = '474a0170e40'

down_revision = '59af27b681f'



from alembic import op

import sqlalchemy as sa



def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notif_idea_by_user',
    sa.Column('notif_id', sa.UUID(), nullable=False),
    sa.Column('user_by', sa.UUID(), nullable=False),
    sa.Column('user_to', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.idea_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_by'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_to'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notif_id')
    )
    ### end Alembic commands ###



def downgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notif_idea_by_user')
    ### end Alembic commands ###

