"""
Users password enabled
Revision ID: 4fdde98983
Revises: ed06d7e2ab
Create Date: 2014-10-12 02:00:46.878188
"""
# revision identifiers, used by Alembic.
revision = '4fdde98983'
down_revision = 'ed06d7e2ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', sa.Column('password', sa.String(length=180), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
