"""
tagging
Revision ID: dfe9914968
Revises: 3f95b7af313
Create Date: 2014-10-17 15:40:45.134501
"""
# revision identifiers, used by Alembic.
revision = 'dfe9914968'
down_revision = '3f95b7af313'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tagging',
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.idea_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'idea_id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tagging')
    ### end Alembic commands ###
