"""
users-and-ideas
Revision ID: ed06d7e2ab
Revises: ab06d5ddd9
Create Date: 2014-09-06 23:00:08.575679
"""
# revision identifiers, used by Alembic.
revision = 'ed06d7e2ab'
down_revision = 'ab06d5ddd9'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea',
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('desc', sa.String(length=1000), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idea_id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idea')
    ### end Alembic commands ###
